In [1]:
import torch
print(torch.version.cuda)
print(torch.cuda.is_available())

None
False

In [2]:
from datasets import ImageDataset, SegmentDataset
from preprocessors import LabeledSegmentsCreator,SuperpixelSegmentsCreator
from models import HistogramBaseModel
import config
import numpy as np
import mlflow
# Initialize the image dataset with the specified paths
image_dataset=ImageDataset(dataset_name="raw_bainite_dataset",
                 image_data_path=config.RAW_BAINITE_IMAGE_DATASET_PATH,
                 image_label_data_path=config.RAW_BAINITE_LABEL_DATASET_PATH,
    )
raw_images_df=image_dataset.load_meta_data()
raw_images_df

,image_path,json_path,martensite_count,bainite_count
0,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,8.0,4.0
1,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,6.0,5.0
2,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,9.0,8.0
3,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,None,NaN,NaN
4,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,None,NaN,NaN
5,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,None,NaN,NaN

In [3]:
raw_images_df = raw_images_df[raw_images_df['json_path'].notnull()]
raw_images_df

,image_path,json_path,martensite_count,bainite_count
0,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,8.0,4.0
1,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,6.0,5.0
2,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,9.0,8.0

In [4]:
# Initialize the segment dataset
segment_dataset = SegmentDataset(dataset_name="raw_bainite_segments",
                                  image_data_path=config.RAW_BAINITE_SEGMENTS_DATASET_PATH,
                                  image_label_data_path=config.RAW_BAINITE_SEGMENTS_LABELS_DATASET_PATH)
# Create the labeled segments
labeled_segments_creator = LabeledSegmentsCreator(input_dataset=image_dataset, output_dataset=segment_dataset)
labeled_segments_creator.create_segments()

Created dir: C:\Users\ja\Desktop\Bainitu_segmenation\data_labeling\src\results\raw_bainite_segments
Warning: No JSON path for C:\Users\ja\Desktop\Bainitu_segmenation\data_labeling\src\raw_images\798-DQ-hollow_1000x-1.tif, skipping...
Warning: No JSON path for C:\Users\ja\Desktop\Bainitu_segmenation\data_labeling\src\raw_images\798-DQ-hollow_1000x-2.tif, skipping...
Warning: No JSON path for C:\Users\ja\Desktop\Bainitu_segmenation\data_labeling\src\raw_images\798-DQ-hollow_1000x-3.tif, skipping...
Created 5 segments from 6 images.

In [5]:
segment_dataset.load_meta_data()

,image_path,json_path,label
0,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
1,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
2,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
3,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
4,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
5,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
6,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
7,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
8,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
9,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
10,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
11,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
12,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
13,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
14,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
15,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
16,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
17,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
18,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
19,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
20,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
21,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
22,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
23,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
24,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
25,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
26,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
27,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
28,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
29,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
30,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,bainite
31,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
32,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
33,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
34,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
35,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
36,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
37,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
38,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite
39,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,C:\Users\ja\Desktop\Bainitu_segmenation\data_l...,martensite

In [ ]:
from optimisers.optuna_optimiser.optuna_optimiser import OptunaOptimiser


model_parameters = {
    'n_estimators': {'type': 'int', 'min': 50, 'max': 200},
    'max_depth': {'type': 'int', 'min': 5, 'max': 20},
    'min_samples_split': {'type': 'int', 'min': 2, 'max': 10},
    'min_samples_leaf': {'type': 'int', 'min': 1, 'max': 5},
    'max_features': {'type': 'int', 'min': 1, 'max': 5},   
    'bins': {'type': 'int', 'min': 64, 'max': 256}
}

slic_parameters = {
        "pixels_per_superpixel" : {'type' : 'int', 'min' : 8000, 'max' : 30000},
        "compactness" : {'type' : 'float', 'min' : 0.4, 'max' : 1}, # consider 0.5
        # "min_cluster_size" : {'type' : 'int', 'min' : 30, 'max' : 100},
        "sigma" : {'type' : 'float', 'min' : 0.1, 'max' : 1.5}
}

felzenszwalb_parameters = {
        # "scale_ratio" : {'type' : 'float', 'min' : 0.00001, 'max' : 0.00005},
        "scale" : {'type' : 'int', 'min' : 30, 'max' : 200},
        "min_size" : {'type' : 'int', 'min' : 10, 'max' : 300},
        "sigma" : {'type' : 'float', 'min' : 0.1, 'max' : 1.5}
}

felzenszwalb_parameters = {
        # "scale_ratio" : {'type' : 'float', 'min' : 0.00001, 'max' : 0.00005},
        "scale" : {'type' : 'int', 'min' : 160, 'max' : 350},
        "min_size" : {'type' : 'int', 'min' : 250, 'max' : 500},
        "sigma" : {'type' : 'float', 'min' : 0.3, 'max' : 0.6}
}

optuna_optimiser_felzenszwalb = OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="HistogramBaseModel", segmentation="felzenszwalb", n_trials=20,
                                   model_hyperparameters=model_parameters, segmentation_parameters = felzenszwalb_parameters, maximize=True, metric_name='f1', experiment_name="Felzenszwalb_min_nonadj_bin_limit_bigger_segments")

In [ ]:
optuna_optimiser_felzenszwalb.optimise()

In [ ]:
from optimisers.optuna_optimiser.optuna_optimiser import OptunaOptimiser


model_parameters = {
    'n_estimators': {'type': 'int', 'min': 50, 'max': 200},
    'max_depth': {'type': 'int', 'min': 5, 'max': 20},
    'min_samples_split': {'type': 'int', 'min': 2, 'max': 10},
    'min_samples_leaf': {'type': 'int', 'min': 1, 'max': 5},
    'max_features': {'type': 'int', 'min': 1, 'max': 5},   
    'bins': {'type': 'int', 'min': 64, 'max': 256}
}

slic_parameters = {
        "pixels_per_superpixel" : {'type' : 'int', 'min' : 10000, 'max' : 30000},
        "compactness" : {'type' : 'float', 'min' : 0.4, 'max' : 0.9}, # consider 0.5
        "sigma" : {'type' : 'float', 'min' : 0.6, 'max' : 1.5}
}


optuna_optimiser_slic = OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="HistogramBaseModel", segmentation="slic", n_trials=100,
                                   model_hyperparameters=model_parameters, segmentation_parameters = slic_parameters, maximize=True, metric_name='f1', experiment_name="Slic_bin_limit_new_data")

In [ ]:
mlflow.end_run()

In [ ]:
optuna_optimiser_slic.optimise()

In [ ]:
from optimisers.optuna_optimiser.optuna_optimiser import OptunaOptimiser


model_parameters = {
    'n_estimators': {'type': 'int', 'min': 50, 'max': 200},
    'max_depth': {'type': 'int', 'min': 5, 'max': 20},
    'min_samples_split': {'type': 'int', 'min': 2, 'max': 10},
    'min_samples_leaf': {'type': 'int', 'min': 1, 'max': 5},
    'max_features': {'type': 'int', 'min': 1, 'max': 5},   
    'bins': {'type': 'int', 'min': 64, 'max': 256}
}

watershed_parameters = {
        "connectivity" : {'type' : 'int', 'min' : 0, 'max' : 4},
}


optuna_optimiser_watershed= OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="HistogramBaseModel", segmentation="watershed", n_trials=30,
                                   model_hyperparameters=model_parameters, segmentation_parameters = watershed_parameters, maximize=True, metric_name='f1', experiment_name="Watershed_bin_limit_new_data")

In [ ]:
optuna_optimiser_watershed.optimise()

In [ ]:
from optimisers.optuna_optimiser.optuna_optimiser import OptunaOptimiser


model_parameters = {
    'lr': {'type': 'float', 'min': 1e-4, 'max': 1e-1},
    'epochs': {'type': 'int', 'min': 2, 'max': 10},
}

slic_parameters = {
        "pixels_per_superpixel" : {'type' : 'int', 'min' : 8000, 'max' : 30000},
        "compactness" : {'type' : 'float', 'min' : 0.4, 'max' : 1}, # consider 0.5
        "sigma" : {'type' : 'float', 'min' : 0.1, 'max' : 1.5}
}

optuna_optimiser= OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="ResNet50", segmentation="slic", n_trials=10,
                                   model_hyperparameters=model_parameters, segmentation_parameters = slic_parameters, maximize=True, metric_name='f1', experiment_name="ResNet50")

In [ ]:
optuna_optimiser.optimise()

In [6]:
from optimisers.optuna_optimiser.optuna_optimiser import OptunaOptimiser


model_parameters = {
    'lr': {'type': 'float', 'min': 1e-4, 'max': 1e-1},
    'epochs': {'type': 'int', 'min': 3, 'max': 100},
}

slic_parameters = {
        "pixels_per_superpixel" : {'type' : 'int', 'min' : 8000, 'max' : 25000},
        "compactness" : {'type' : 'float', 'min' : 0.6, 'max' : 0.8}, # consider 0.5
        "sigma" : {'type' : 'float', 'min' : 0.1, 'max' : 1.5}
}

optuna_optimiser= OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="efficientnet_b0", segmentation="slic", n_trials=100,
                                   model_hyperparameters=model_parameters, segmentation_parameters = slic_parameters, maximize=True, metric_name='f1', experiment_name="efficientnet_b0")
optuna_optimiser.optimise()

c:\Users\ja\Desktop\Bainitu_segmenation\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025/10/30 19:14:27 INFO mlflow.tracking.fluent: Experiment with name 'efficientnet_b05e91a118-50fc-433a-a2fc-727e8575ac80' does not exist. Creating a new experiment.
[I 2025-10-30 19:14:27,147] A new study created in memory with name: no-name-9c33483e-c09e-46b1-88f9-2a89e8ce594c

Created dir: C:\Users\ja\Desktop\Bainitu_segmenation\data_labeling\src\results\slic_2b5353806886
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_martensitic_segment_counter
Label correct: martensite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter
Label correct: bainite
Increased local_bainitic_segment_counter

Fold 1, Epoch 1, Loss: 1.1709

Fold 1, Epoch 2, Loss: 0.5873

Fold 1, Epoch 3, Loss: 0.5941

Fold 1, Epoch 4, Loss: 0.4221

Fold 1, Epoch 5, Loss: 0.3327

Fold 1, Epoch 6, Loss: 0.3098

Fold 1, Epoch 7, Loss: 0.3658

Fold 1, Epoch 8, Loss: 0.2668

Fold 1, Epoch 9, Loss: 0.3798

Fold 1, Epoch 10, Loss: 0.2316

Fold 1, Epoch 11, Loss: 0.1694

Fold 1, Epoch 12, Loss: 0.2771

Fold 1, Epoch 13, Loss: 0.1970

Fold 1, Epoch 14, Loss: 0.1842

Fold 1, Epoch 15, Loss: 0.1216

Fold 1, Epoch 16, Loss: 0.1401

Fold 1, Epoch 17, Loss: 0.1212

Fold 1, Epoch 18, Loss: 0.1560

Fold 1, Epoch 19, Loss: 0.2506

Fold 1, Epoch 20, Loss: 0.1123

Fold 1, Epoch 21, Loss: 0.1343

Fold 1, Epoch 22, Loss: 0.1768

Fold 1, Epoch 23, Loss: 0.1143

Fold 1, Epoch 24, Loss: 0.0968

Fold 1, Epoch 25, Loss: 0.2038

Fold 1, Epoch 26, Loss: 0.1360

Fold 1, Epoch 27, Loss: 0.1051

Fold 1, Epoch 28, Loss: 0.1558

Fold 1, Epoch 29, Loss: 0.1614

Fold 1, Epoch 30, Loss: 0.1490

Fold 1, Epoch 31, Loss: 0.3298

Fold 1, Epoch 32, Loss: 0.0762

Fold 1, Epoch 33, Loss: 0.2002

Fold 1, Epoch 34, Loss: 0.1242

Fold 1, Epoch 35, Loss: 0.1202

Fold 1, Epoch 36, Loss: 0.1841

Fold 1, Epoch 37, Loss: 0.1692

Fold 1, Epoch 38, Loss: 0.0682

Fold 1, Epoch 39, Loss: 0.0744

Fold 1, Epoch 40, Loss: 0.1094

Fold 1, Epoch 41, Loss: 0.1135

Fold 1, Epoch 42, Loss: 0.1634

Fold 1, Epoch 43, Loss: 0.0525

Fold 1, Epoch 44, Loss: 0.0777

Fold 1, Epoch 45, Loss: 0.0783

Fold 1, Epoch 46, Loss: 0.0665

Fold 1, Epoch 47, Loss: 0.0603

Fold 1, Epoch 48, Loss: 0.0963

Fold 1, Epoch 49, Loss: 0.0763

Fold 1, Epoch 50, Loss: 0.1251

Fold 1, Epoch 51, Loss: 0.1225

Fold 1, Epoch 52, Loss: 0.0872

Fold 1, Epoch 53, Loss: 0.1077

Fold 1, Epoch 54, Loss: 0.0783

Fold 1, Epoch 55, Loss: 0.0885

Fold 1, Epoch 56, Loss: 0.1346

Fold 1, Epoch 57, Loss: 0.1068

Fold 1, Epoch 58, Loss: 0.1620

Fold 1, Epoch 59, Loss: 0.0247

Fold 1, Epoch 60, Loss: 0.1058

Fold 1, Epoch 61, Loss: 0.0787

Fold 1, Epoch 62, Loss: 0.0719

Fold 1, Epoch 63, Loss: 0.1008

Fold 1, Epoch 64, Loss: 0.0413

Fold 1, Epoch 65, Loss: 0.0819

Fold 1, Epoch 66, Loss: 0.1705

Fold 1, Epoch 67, Loss: 0.0695

Fold 1, Epoch 68, Loss: 0.0387

Fold 1, Epoch 69, Loss: 0.1843

Fold 1, Epoch 70, Loss: 0.0785

Fold 1, Epoch 71, Loss: 0.0685

Fold 1, Epoch 72, Loss: 0.1178

Fold 1, Epoch 73, Loss: 0.0733

Fold 1, Epoch 74, Loss: 0.0572

Fold 1, Epoch 75, Loss: 0.2096

Fold 1, Epoch 76, Loss: 0.1323

Fold 1, Epoch 77, Loss: 0.0264

Fold 1, Epoch 78, Loss: 0.0980

Fold 1, Epoch 79, Loss: 0.0395

Fold 1, Epoch 80, Loss: 0.0424

Fold 1, Epoch 81, Loss: 0.1641

Fold 1, Epoch 82, Loss: 0.1470

Fold 1, Epoch 83, Loss: 0.0628

Fold 1, Epoch 84, Loss: 0.0322

Fold 1, Epoch 85, Loss: 0.0704

Fold 1, Epoch 86, Loss: 0.1721

Fold 1, Epoch 87, Loss: 0.0678

Fold 1, Epoch 88, Loss: 0.0574

Fold 1, Epoch 89, Loss: 0.0854

Fold 1, Epoch 90, Loss: 0.2138

Fold 1, Epoch 91, Loss: 0.0663

Fold 1, Epoch 92, Loss: 0.1158

Fold 1, Epoch 93, Loss: 0.3957

Fold 1, Epoch 94, Loss: 0.0511

Fold 1, Epoch 95, Loss: 0.0400

Fold 1, Epoch 96, Loss: 0.0346

---- Fold 2/5 ----

Fold 2, Epoch 1, Loss: 1.0032

Fold 2, Epoch 2, Loss: 0.6103

Fold 2, Epoch 3, Loss: 0.4447

Fold 2, Epoch 4, Loss: 0.4346

Fold 2, Epoch 5, Loss: 0.4305

Fold 2, Epoch 6, Loss: 0.2861

Fold 2, Epoch 7, Loss: 0.2346

Fold 2, Epoch 8, Loss: 0.2059

Fold 2, Epoch 9, Loss: 0.2206

Fold 2, Epoch 10, Loss: 0.1490

Fold 2, Epoch 11, Loss: 0.1489

Fold 2, Epoch 12, Loss: 0.1996

Fold 2, Epoch 13, Loss: 0.1223

Fold 2, Epoch 14, Loss: 0.1252

Fold 2, Epoch 15, Loss: 0.1297

Fold 2, Epoch 16, Loss: 0.1020

Fold 2, Epoch 17, Loss: 0.1493

Fold 2, Epoch 18, Loss: 0.2782

Fold 2, Epoch 19, Loss: 0.0883

Fold 2, Epoch 20, Loss: 0.1509

Fold 2, Epoch 21, Loss: 0.1197

Fold 2, Epoch 22, Loss: 0.1284

Fold 2, Epoch 23, Loss: 0.0905

Fold 2, Epoch 24, Loss: 0.1246

Fold 2, Epoch 25, Loss: 0.0511

Fold 2, Epoch 26, Loss: 0.1205

Fold 2, Epoch 27, Loss: 0.1127

Fold 2, Epoch 28, Loss: 0.0425

Fold 2, Epoch 29, Loss: 0.0584

Fold 2, Epoch 30, Loss: 0.0936

Fold 2, Epoch 31, Loss: 0.0565

Fold 2, Epoch 32, Loss: 0.0641

Fold 2, Epoch 33, Loss: 0.0377

Fold 2, Epoch 34, Loss: 0.0307

Fold 2, Epoch 35, Loss: 0.0418

Fold 2, Epoch 36, Loss: 0.0966

Fold 2, Epoch 37, Loss: 0.0979

Fold 2, Epoch 38, Loss: 0.0604

Fold 2, Epoch 39, Loss: 0.0434

Fold 2, Epoch 40, Loss: 0.0190

Fold 2, Epoch 41, Loss: 0.0977

Fold 2, Epoch 42, Loss: 0.1334

Fold 2, Epoch 43, Loss: 0.0723

Fold 2, Epoch 44, Loss: 0.0303

Fold 2, Epoch 45, Loss: 0.1994

Fold 2, Epoch 46, Loss: 0.0720

Fold 2, Epoch 47, Loss: 0.1090

Fold 2, Epoch 48, Loss: 0.1097

Fold 2, Epoch 49, Loss: 0.0474

Fold 2, Epoch 50, Loss: 0.0247

Fold 2, Epoch 51, Loss: 0.1562

Fold 2, Epoch 52, Loss: 0.0484

Fold 2, Epoch 53, Loss: 0.0911

Fold 2, Epoch 54, Loss: 0.0930

Fold 2, Epoch 55, Loss: 0.1085

Fold 2, Epoch 56, Loss: 0.1840

Fold 2, Epoch 57, Loss: 0.1737

Fold 2, Epoch 58, Loss: 0.0576

Fold 2, Epoch 59, Loss: 0.0918

Fold 2, Epoch 60, Loss: 0.1405

Fold 2, Epoch 61, Loss: 0.0850

Fold 2, Epoch 62, Loss: 0.1127

Fold 2, Epoch 63, Loss: 0.0910

Fold 2, Epoch 64, Loss: 0.1067

Fold 2, Epoch 65, Loss: 0.1108

Fold 2, Epoch 66, Loss: 0.0637

Fold 2, Epoch 67, Loss: 0.0352

Fold 2, Epoch 68, Loss: 0.0585

Fold 2, Epoch 69, Loss: 0.1137

Fold 2, Epoch 70, Loss: 0.1033

Fold 2, Epoch 71, Loss: 0.1555

Fold 2, Epoch 72, Loss: 0.0895

Fold 2, Epoch 73, Loss: 0.0566

Fold 2, Epoch 74, Loss: 0.1171

Fold 2, Epoch 75, Loss: 0.1310

Fold 2, Epoch 76, Loss: 0.0936

Fold 2, Epoch 77, Loss: 0.0801

Fold 2, Epoch 78, Loss: 0.0975

Fold 2, Epoch 79, Loss: 0.0451

Fold 2, Epoch 80, Loss: 0.0350

Fold 2, Epoch 81, Loss: 0.0596

Fold 2, Epoch 82, Loss: 0.0916

Fold 2, Epoch 83, Loss: 0.0474

Fold 2, Epoch 84, Loss: 0.0396

Fold 2, Epoch 85, Loss: 0.0467

Fold 2, Epoch 86, Loss: 0.0643

Fold 2, Epoch 87, Loss: 0.1948

Fold 2, Epoch 88, Loss: 0.0694

Fold 2, Epoch 89, Loss: 0.0893

Fold 2, Epoch 90, Loss: 0.0915

Fold 2, Epoch 91, Loss: 0.1125

Fold 2, Epoch 92, Loss: 0.0280

Fold 2, Epoch 93, Loss: 0.0607

Fold 2, Epoch 94, Loss: 0.0965

Fold 2, Epoch 95, Loss: 0.0218

Fold 2, Epoch 96, Loss: 0.0551

---- Fold 3/5 ----

Fold 3, Epoch 1, Loss: 0.7390

Fold 3, Epoch 2, Loss: 0.4920

Fold 3, Epoch 3, Loss: 0.6065

Fold 3, Epoch 4, Loss: 0.3065

Fold 3, Epoch 5, Loss: 0.2286

Fold 3, Epoch 6, Loss: 0.2471

Fold 3, Epoch 7, Loss: 0.2011

Fold 3, Epoch 8, Loss: 0.3023

Fold 3, Epoch 9, Loss: 0.2091

Fold 3, Epoch 10, Loss: 0.1733

Fold 3, Epoch 11, Loss: 0.1194

Fold 3, Epoch 12, Loss: 0.2005

Fold 3, Epoch 13, Loss: 0.1437

Fold 3, Epoch 14, Loss: 0.2170

Fold 3, Epoch 15, Loss: 0.1081

Fold 3, Epoch 16, Loss: 0.1002

Fold 3, Epoch 17, Loss: 0.1451

Fold 3, Epoch 18, Loss: 0.0968

Fold 3, Epoch 19, Loss: 0.1222

Fold 3, Epoch 20, Loss: 0.0667

Fold 3, Epoch 21, Loss: 0.0859

Fold 3, Epoch 22, Loss: 0.1613

Fold 3, Epoch 23, Loss: 0.1101

Fold 3, Epoch 24, Loss: 0.1240

Fold 3, Epoch 25, Loss: 0.0665

Fold 3, Epoch 26, Loss: 0.1531

Fold 3, Epoch 27, Loss: 0.0803

Fold 3, Epoch 28, Loss: 0.0481

Fold 3, Epoch 29, Loss: 0.1314

Fold 3, Epoch 30, Loss: 0.2570

Fold 3, Epoch 31, Loss: 0.0888

Fold 3, Epoch 32, Loss: 0.0414

Fold 3, Epoch 33, Loss: 0.1708

Fold 3, Epoch 34, Loss: 0.0781

Fold 3, Epoch 35, Loss: 0.0496

Fold 3, Epoch 36, Loss: 0.1584

Fold 3, Epoch 37, Loss: 0.0913

Fold 3, Epoch 38, Loss: 0.0800

Fold 3, Epoch 39, Loss: 0.0697

Fold 3, Epoch 40, Loss: 0.1578

Fold 3, Epoch 41, Loss: 0.0498

Fold 3, Epoch 42, Loss: 0.4188

Fold 3, Epoch 43, Loss: 0.0743

Fold 3, Epoch 44, Loss: 0.0946

Fold 3, Epoch 45, Loss: 0.2943

Fold 3, Epoch 46, Loss: 0.0599

Fold 3, Epoch 47, Loss: 0.1353

Fold 3, Epoch 48, Loss: 0.0809

Fold 3, Epoch 49, Loss: 0.1474

Fold 3, Epoch 50, Loss: 0.1982

Fold 3, Epoch 51, Loss: 0.0438

Fold 3, Epoch 52, Loss: 0.0434

Fold 3, Epoch 53, Loss: 0.0422

Fold 3, Epoch 54, Loss: 0.1555

Fold 3, Epoch 55, Loss: 0.1023

Fold 3, Epoch 56, Loss: 0.0755

Fold 3, Epoch 57, Loss: 0.0868

Fold 3, Epoch 58, Loss: 0.0493

Fold 3, Epoch 59, Loss: 0.0236

Fold 3, Epoch 60, Loss: 0.0408

Fold 3, Epoch 61, Loss: 0.0167

Fold 3, Epoch 62, Loss: 0.1281

Fold 3, Epoch 63, Loss: 0.0570

Fold 3, Epoch 64, Loss: 0.0370

Fold 3, Epoch 65, Loss: 0.0891

Fold 3, Epoch 66, Loss: 0.2044

Fold 3, Epoch 67, Loss: 0.1226

Fold 3, Epoch 68, Loss: 0.0619

Fold 3, Epoch 69, Loss: 0.0455

Fold 3, Epoch 70, Loss: 0.1001

Fold 3, Epoch 71, Loss: 0.1549

Fold 3, Epoch 72, Loss: 0.0370

Fold 3, Epoch 73, Loss: 0.0420

Fold 3, Epoch 74, Loss: 0.1308

Fold 3, Epoch 75, Loss: 0.0542

Fold 3, Epoch 76, Loss: 0.1508

Fold 3, Epoch 77, Loss: 0.1212

Fold 3, Epoch 78, Loss: 0.0714

Fold 3, Epoch 79, Loss: 0.0691

Fold 3, Epoch 80, Loss: 0.0766

Fold 3, Epoch 81, Loss: 0.0205

Fold 3, Epoch 82, Loss: 0.0574

Fold 3, Epoch 83, Loss: 0.0264

Fold 3, Epoch 84, Loss: 0.0535

Fold 3, Epoch 85, Loss: 0.0297

Fold 3, Epoch 86, Loss: 0.0778

Fold 3, Epoch 87, Loss: 0.0366

Fold 3, Epoch 88, Loss: 0.1365

Fold 3, Epoch 89, Loss: 0.0304

Fold 3, Epoch 90, Loss: 0.0826

Fold 3, Epoch 91, Loss: 0.0479

Fold 3, Epoch 92, Loss: 0.0492

Fold 3, Epoch 93, Loss: 0.1810

Fold 3, Epoch 94, Loss: 0.0155

Fold 3, Epoch 95, Loss: 0.0476

Fold 3, Epoch 96, Loss: 0.0769

---- Fold 4/5 ----

Fold 4, Epoch 1, Loss: 0.9965

Fold 4, Epoch 2, Loss: 0.6054

Fold 4, Epoch 3, Loss: 0.6808

Fold 4, Epoch 4, Loss: 0.3745

Fold 4, Epoch 5, Loss: 0.4424

Fold 4, Epoch 6, Loss: 0.3969

Fold 4, Epoch 7, Loss: 0.3558

Fold 4, Epoch 8, Loss: 0.2160

Fold 4, Epoch 9, Loss: 0.3330

Fold 4, Epoch 10, Loss: 0.1697

Fold 4, Epoch 11, Loss: 0.1957

Fold 4, Epoch 12, Loss: 0.1313

Fold 4, Epoch 13, Loss: 0.0968

Fold 4, Epoch 14, Loss: 0.1648

Fold 4, Epoch 15, Loss: 0.1702

Fold 4, Epoch 16, Loss: 0.1077

Fold 4, Epoch 17, Loss: 0.1016

Fold 4, Epoch 18, Loss: 0.1934

Fold 4, Epoch 19, Loss: 0.0905

Fold 4, Epoch 20, Loss: 0.1530

Fold 4, Epoch 21, Loss: 0.1401

Fold 4, Epoch 22, Loss: 0.1134

Fold 4, Epoch 23, Loss: 0.0868

Fold 4, Epoch 24, Loss: 0.1429

Fold 4, Epoch 25, Loss: 0.1028

Fold 4, Epoch 26, Loss: 0.0704

Fold 4, Epoch 27, Loss: 0.1908

Fold 4, Epoch 28, Loss: 0.1652

Fold 4, Epoch 29, Loss: 0.1359

Fold 4, Epoch 30, Loss: 0.0988

Fold 4, Epoch 31, Loss: 0.1503

Fold 4, Epoch 32, Loss: 0.0536

Fold 4, Epoch 33, Loss: 0.1456

Fold 4, Epoch 34, Loss: 0.0614

Fold 4, Epoch 35, Loss: 0.0847

Fold 4, Epoch 36, Loss: 0.1097

Fold 4, Epoch 37, Loss: 0.1283

Fold 4, Epoch 38, Loss: 0.0687

Fold 4, Epoch 39, Loss: 0.0708

Fold 4, Epoch 40, Loss: 0.0482

Fold 4, Epoch 41, Loss: 0.0780

Fold 4, Epoch 42, Loss: 0.0818

Fold 4, Epoch 43, Loss: 0.0910

Fold 4, Epoch 44, Loss: 0.0745

Fold 4, Epoch 45, Loss: 0.0463

Fold 4, Epoch 46, Loss: 0.1561

Fold 4, Epoch 47, Loss: 0.0708

Fold 4, Epoch 48, Loss: 0.1031

Fold 4, Epoch 49, Loss: 0.1060

Fold 4, Epoch 50, Loss: 0.0767

Fold 4, Epoch 51, Loss: 0.0281

Fold 4, Epoch 52, Loss: 0.0989

Fold 4, Epoch 53, Loss: 0.0492

Fold 4, Epoch 54, Loss: 0.0448

Fold 4, Epoch 55, Loss: 0.1104

Fold 4, Epoch 56, Loss: 0.1344

Fold 4, Epoch 57, Loss: 0.1108

Fold 4, Epoch 58, Loss: 0.0962

Fold 4, Epoch 59, Loss: 0.0393

Fold 4, Epoch 60, Loss: 0.0508

Fold 4, Epoch 61, Loss: 0.0318

Fold 4, Epoch 62, Loss: 0.0866

Fold 4, Epoch 63, Loss: 0.0556

Fold 4, Epoch 64, Loss: 0.1622

Fold 4, Epoch 65, Loss: 0.1012

Fold 4, Epoch 66, Loss: 0.0418

Fold 4, Epoch 67, Loss: 0.0543

Fold 4, Epoch 68, Loss: 0.2063

Fold 4, Epoch 69, Loss: 0.0456

Fold 4, Epoch 70, Loss: 0.0627

Fold 4, Epoch 71, Loss: 0.0682

Fold 4, Epoch 72, Loss: 0.1011

Fold 4, Epoch 73, Loss: 0.0478

Fold 4, Epoch 74, Loss: 0.0962

Fold 4, Epoch 75, Loss: 0.0381

Fold 4, Epoch 76, Loss: 0.0484

Fold 4, Epoch 77, Loss: 0.0965

Fold 4, Epoch 78, Loss: 0.0713

Fold 4, Epoch 79, Loss: 0.0629

Fold 4, Epoch 80, Loss: 0.0616

Fold 4, Epoch 81, Loss: 0.0832

Fold 4, Epoch 82, Loss: 0.0846

Fold 4, Epoch 83, Loss: 0.1090

Fold 4, Epoch 84, Loss: 0.0734

Fold 4, Epoch 85, Loss: 0.0851

Fold 4, Epoch 86, Loss: 0.1398

Fold 4, Epoch 87, Loss: 0.0719

Fold 4, Epoch 88, Loss: 0.1265

Fold 4, Epoch 89, Loss: 0.0379

Fold 4, Epoch 90, Loss: 0.1373

Fold 4, Epoch 91, Loss: 0.0998

Fold 4, Epoch 92, Loss: 0.0230

Fold 4, Epoch 93, Loss: 0.0319

Fold 4, Epoch 94, Loss: 0.0458

Fold 4, Epoch 95, Loss: 0.0585

Fold 4, Epoch 96, Loss: 0.2477

---- Fold 5/5 ----

Fold 5, Epoch 1, Loss: 0.6284

Fold 5, Epoch 2, Loss: 0.4447

Fold 5, Epoch 3, Loss: 0.3457

Fold 5, Epoch 4, Loss: 0.2857

Fold 5, Epoch 5, Loss: 0.2518

Fold 5, Epoch 6, Loss: 0.3421

Fold 5, Epoch 7, Loss: 0.1861

Fold 5, Epoch 8, Loss: 0.3151

Fold 5, Epoch 9, Loss: 0.3152

Fold 5, Epoch 10, Loss: 0.0917

Fold 5, Epoch 11, Loss: 0.2757

Fold 5, Epoch 12, Loss: 0.1872

Fold 5, Epoch 13, Loss: 0.1449

Fold 5, Epoch 14, Loss: 0.1712

Fold 5, Epoch 15, Loss: 0.1231

Fold 5, Epoch 16, Loss: 0.0934

Fold 5, Epoch 17, Loss: 0.1772

Fold 5, Epoch 18, Loss: 0.1420

Fold 5, Epoch 19, Loss: 0.2843

Fold 5, Epoch 20, Loss: 0.1067

Fold 5, Epoch 21, Loss: 0.2612

Fold 5, Epoch 22, Loss: 0.1596

Fold 5, Epoch 23, Loss: 0.0398

Fold 5, Epoch 24, Loss: 0.1910

Fold 5, Epoch 25, Loss: 0.1537

Fold 5, Epoch 26, Loss: 0.1531

Fold 5, Epoch 27, Loss: 0.0816

Fold 5, Epoch 28, Loss: 0.0640

Fold 5, Epoch 29, Loss: 0.0344

Fold 5, Epoch 30, Loss: 0.0750

Fold 5, Epoch 31, Loss: 0.1200

Fold 5, Epoch 32, Loss: 0.0804

Fold 5, Epoch 33, Loss: 0.0592

Fold 5, Epoch 34, Loss: 0.1265

Fold 5, Epoch 35, Loss: 0.1204

Fold 5, Epoch 36, Loss: 0.0932

Fold 5, Epoch 37, Loss: 0.0408

Fold 5, Epoch 38, Loss: 0.0584

Fold 5, Epoch 39, Loss: 0.2312

Fold 5, Epoch 40, Loss: 0.0611

Fold 5, Epoch 41, Loss: 0.0673

Fold 5, Epoch 42, Loss: 0.0454

Fold 5, Epoch 43, Loss: 0.0534

Fold 5, Epoch 44, Loss: 0.0350

Fold 5, Epoch 45, Loss: 0.0727

Fold 5, Epoch 46, Loss: 0.0509

Fold 5, Epoch 47, Loss: 0.0363

Fold 5, Epoch 48, Loss: 0.0282

Fold 5, Epoch 49, Loss: 0.0829

Fold 5, Epoch 50, Loss: 0.1686

Fold 5, Epoch 51, Loss: 0.1742

Fold 5, Epoch 52, Loss: 0.1209

Fold 5, Epoch 53, Loss: 0.0796

Fold 5, Epoch 54, Loss: 0.0391

Fold 5, Epoch 55, Loss: 0.0565

Fold 5, Epoch 56, Loss: 0.2243

Fold 5, Epoch 57, Loss: 0.0641

Fold 5, Epoch 58, Loss: 0.0474

Fold 5, Epoch 59, Loss: 0.0849

Fold 5, Epoch 60, Loss: 0.0652

Fold 5, Epoch 61, Loss: 0.0172

Fold 5, Epoch 62, Loss: 0.1413

Fold 5, Epoch 63, Loss: 0.0217

Fold 5, Epoch 64, Loss: 0.0669

Fold 5, Epoch 65, Loss: 0.0575

Fold 5, Epoch 66, Loss: 0.0317

Fold 5, Epoch 67, Loss: 0.0604

Fold 5, Epoch 68, Loss: 0.0370

Fold 5, Epoch 69, Loss: 0.0154

Fold 5, Epoch 70, Loss: 0.0328

Fold 5, Epoch 71, Loss: 0.0528

Fold 5, Epoch 72, Loss: 0.0589

Fold 5, Epoch 73, Loss: 0.0704

Fold 5, Epoch 74, Loss: 0.1255

Fold 5, Epoch 75, Loss: 0.0713

Fold 5, Epoch 76, Loss: 0.0151

Fold 5, Epoch 77, Loss: 0.1260

Fold 5, Epoch 78, Loss: 0.5195

Fold 5, Epoch 79, Loss: 0.0736

Fold 5, Epoch 80, Loss: 0.0618

Fold 5, Epoch 81, Loss: 0.2003

Fold 5, Epoch 82, Loss: 0.1337

Fold 5, Epoch 83, Loss: 0.1658

Fold 5, Epoch 84, Loss: 0.0927

Fold 5, Epoch 85, Loss: 0.0551

Fold 5, Epoch 86, Loss: 0.1685

Fold 5, Epoch 87, Loss: 0.3706

Fold 5, Epoch 88, Loss: 0.1448

Fold 5, Epoch 89, Loss: 0.0610

Fold 5, Epoch 90, Loss: 0.0951

Fold 5, Epoch 91, Loss: 0.0528

Fold 5, Epoch 92, Loss: 0.0847

Fold 5, Epoch 93, Loss: 0.0748

Fold 5, Epoch 94, Loss: 0.1446

Fold 5, Epoch 95, Loss: 0.1118

Fold 5, Epoch 96, Loss: 0.0700

[W 2025-10-30 19:36:29,825] Trial 0 failed with parameters: {'lr': 0.009864308836166928, 'epochs': 96, 'pixels_per_superpixel': 23093, 'compactness': 0.7038576165600896, 'sigma': 0.7285315664993129} because of the following error: AttributeError("type object 'EfficientNet_B0_Weights' has no attribute 'IMAGENET1K_V2'").
Traceback (most recent call last):
  File "c:\Users\ja\Desktop\Bainitu_segmenation\.venv\Lib\site-packages\optuna\study\_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "c:\Users\ja\Desktop\Bainitu_segmenation\experiment_platform\backend\experiment_platform_backend\optimisers\optuna_optimiser\optuna_optimiser.py", line 144, in objective
    metric,_,_=self.model.train(X, y)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ja\Desktop\Bainitu_segmenation\experiment_platform\backend\experiment_platform_backend\models\BaseModel\efficient_net_b0.py", line 95, in train
    model = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.IMAGENET1K_V2)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'EfficientNet_B0_Weights' has no attribute 'IMAGENET1K_V2'. Did you mean: 'IMAGENET1K_V1'?
[W 2025-10-30 19:36:29,852] Trial 0 failed with value None.

Training final model on full dataset...

AttributeError: type object 'EfficientNet_B0_Weights' has no attribute 'IMAGENET1K_V2'

In [ ]:
!pip install torchvision

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import io
from PIL import Image
def plot_confusion_matrix(cm, labels):

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=labels, yticklabels=labels)
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    plt.close()
    buf.seek(0)

    # Convert buffer to a PIL Image for MLflow
    img = Image.open(buf)
    return img


img=plot_confusion_matrix(cm, labels)
img.show()

In [ ]:
segment_dataset = SegmentDataset(dataset_name="slic_00e6a9d78e98",
                                  image_data_path=config.SUPERPIXEL_BAINITE_SEGMENTS_DATASET_PATH,
                                  image_label_data_path=config.SUPERPIXEL_BAINITE_SEGMENTS_DATASET_PATH)
# Create the labeled segments
labeled_segments_creator = LabeledSegmentsCreator(input_dataset=image_dataset, output_dataset=segment_dataset)
labeled_segments_creator.create_segments()

In [ ]:
import numpy as np

data = np.random.randn(10)
print(data)

hist, bin_edges = np.histogram(data, bins=10)
print(hist)
print(bin_edges)

In [ ]:
import matplotlib.pyplot as plt

plt.hist(data, bins=10, edgecolor='black')
plt.show()

In [ ]:
import cv2
from skimage.segmentation import felzenszwalb
from skimage.segmentation import mark_boundaries
from skimage.util import img_as_float
import matplotlib.pyplot as plt

image = cv2.imread(r"C:\Users\hallo\Desktop\Bainitu_segmenation\data_labeling\src\raw_images\797-DQ-full_1000x-1.tif")
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)[:300]
# Convert to float for segmentation (values between 0 and 1) TODO ???
img_float = img_as_float(gray)
segments = felzenszwalb(
    img_float,
    scale=800,
    #sigma=1,
)
fig, ax = plt.subplots(2, 2, figsize=(10, 10), sharex=True, sharey=True)

ax[0, 0].imshow(mark_boundaries(img_float, segments))
ax[0, 0].set_title("Felzenszwalbs's method")

for a in ax.ravel():
    a.set_axis_off()

plt.tight_layout()
plt.show()